/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisaRouteImport } from './routes/visa'
import { Route as UsaRouteImport } from './routes/usa'
import { Route as UmrahRouteImport } from './routes/umrah'
import { Route as UkRouteImport } from './routes/uk'
import { Route as UaeRouteImport } from './routes/uae'
import { Route as TurkeyTripRouteImport } from './routes/turkey-trip'
import { Route as SyriaRouteImport } from './routes/syria'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SchengenRouteImport } from './routes/schengen'
import { Route as SaudiRouteImport } from './routes/saudi'
import { Route as QatarRouteImport } from './routes/qatar'
import { Route as HajjRouteImport } from './routes/hajj'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as EgyptRouteImport } from './routes/egypt'
import { Route as DubaiRouteImport } from './routes/dubai'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UmrahIndexRouteImport } from './routes/umrah.index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as VisaSlugRouteImport } from './routes/visa.$slug'
import { Route as UmrahIdRouteImport } from './routes/umrah.$id'
import { Route as TripsIdRouteImport } from './routes/trips.$id'
import { Route as PackagesSlugRouteImport } from './routes/packages.$slug'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminVisasIndexRouteImport } from './routes/admin/visas/index'
import { Route as AdminUmrahIndexRouteImport } from './routes/admin/umrah/index'
import { Route as AdminTripsIndexRouteImport } from './routes/admin/trips/index'
import { Route as AdminSettingsIndexRouteImport } from './routes/admin/settings/index'
import { Route as AdminPackagesIndexRouteImport } from './routes/admin/packages/index'
import { Route as AdminHajjIndexRouteImport } from './routes/admin/hajj/index'
import { Route as AdminGalleryIndexRouteImport } from './routes/admin/gallery/index'
import { Route as AdminEgyptIndexRouteImport } from './routes/admin/egypt/index'
import { Route as AdminDubaiIndexRouteImport } from './routes/admin/dubai/index'
import { Route as AdminPackagesSlugRouteImport } from './routes/admin/packages/$slug'

const VisaRoute = VisaRouteImport.update({
  id: '/visa',
  path: '/visa',
  getParentRoute: () => rootRouteImport,
} as any)
const UsaRoute = UsaRouteImport.update({
  id: '/usa',
  path: '/usa',
  getParentRoute: () => rootRouteImport,
} as any)
const UmrahRoute = UmrahRouteImport.update({
  id: '/umrah',
  path: '/umrah',
  getParentRoute: () => rootRouteImport,
} as any)
const UkRoute = UkRouteImport.update({
  id: '/uk',
  path: '/uk',
  getParentRoute: () => rootRouteImport,
} as any)
const UaeRoute = UaeRouteImport.update({
  id: '/uae',
  path: '/uae',
  getParentRoute: () => rootRouteImport,
} as any)
const TurkeyTripRoute = TurkeyTripRouteImport.update({
  id: '/turkey-trip',
  path: '/turkey-trip',
  getParentRoute: () => rootRouteImport,
} as any)
const SyriaRoute = SyriaRouteImport.update({
  id: '/syria',
  path: '/syria',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SchengenRoute = SchengenRouteImport.update({
  id: '/schengen',
  path: '/schengen',
  getParentRoute: () => rootRouteImport,
} as any)
const SaudiRoute = SaudiRouteImport.update({
  id: '/saudi',
  path: '/saudi',
  getParentRoute: () => rootRouteImport,
} as any)
const QatarRoute = QatarRouteImport.update({
  id: '/qatar',
  path: '/qatar',
  getParentRoute: () => rootRouteImport,
} as any)
const HajjRoute = HajjRouteImport.update({
  id: '/hajj',
  path: '/hajj',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const EgyptRoute = EgyptRouteImport.update({
  id: '/egypt',
  path: '/egypt',
  getParentRoute: () => rootRouteImport,
} as any)
const DubaiRoute = DubaiRouteImport.update({
  id: '/dubai',
  path: '/dubai',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UmrahIndexRoute = UmrahIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UmrahRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const VisaSlugRoute = VisaSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => VisaRoute,
} as any)
const UmrahIdRoute = UmrahIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => UmrahRoute,
} as any)
const TripsIdRoute = TripsIdRouteImport.update({
  id: '/trips/$id',
  path: '/trips/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesSlugRoute = PackagesSlugRouteImport.update({
  id: '/packages/$slug',
  path: '/packages/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVisasIndexRoute = AdminVisasIndexRouteImport.update({
  id: '/admin/visas/',
  path: '/admin/visas/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUmrahIndexRoute = AdminUmrahIndexRouteImport.update({
  id: '/admin/umrah/',
  path: '/admin/umrah/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTripsIndexRoute = AdminTripsIndexRouteImport.update({
  id: '/admin/trips/',
  path: '/admin/trips/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsIndexRoute = AdminSettingsIndexRouteImport.update({
  id: '/admin/settings/',
  path: '/admin/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPackagesIndexRoute = AdminPackagesIndexRouteImport.update({
  id: '/admin/packages/',
  path: '/admin/packages/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHajjIndexRoute = AdminHajjIndexRouteImport.update({
  id: '/admin/hajj/',
  path: '/admin/hajj/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGalleryIndexRoute = AdminGalleryIndexRouteImport.update({
  id: '/admin/gallery/',
  path: '/admin/gallery/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEgyptIndexRoute = AdminEgyptIndexRouteImport.update({
  id: '/admin/egypt/',
  path: '/admin/egypt/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDubaiIndexRoute = AdminDubaiIndexRouteImport.update({
  id: '/admin/dubai/',
  path: '/admin/dubai/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPackagesSlugRoute = AdminPackagesSlugRouteImport.update({
  id: '/admin/packages/$slug',
  path: '/admin/packages/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dubai': typeof DubaiRoute
  '/egypt': typeof EgyptRoute
  '/gallery': typeof GalleryRoute
  '/hajj': typeof HajjRoute
  '/qatar': typeof QatarRoute
  '/saudi': typeof SaudiRoute
  '/schengen': typeof SchengenRoute
  '/services': typeof ServicesRoute
  '/syria': typeof SyriaRoute
  '/turkey-trip': typeof TurkeyTripRoute
  '/uae': typeof UaeRoute
  '/uk': typeof UkRoute
  '/umrah': typeof UmrahRouteWithChildren
  '/usa': typeof UsaRoute
  '/visa': typeof VisaRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/packages/$slug': typeof PackagesSlugRoute
  '/trips/$id': typeof TripsIdRoute
  '/umrah/$id': typeof UmrahIdRoute
  '/visa/$slug': typeof VisaSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/umrah/': typeof UmrahIndexRoute
  '/admin/packages/$slug': typeof AdminPackagesSlugRoute
  '/admin/dubai/': typeof AdminDubaiIndexRoute
  '/admin/egypt/': typeof AdminEgyptIndexRoute
  '/admin/gallery/': typeof AdminGalleryIndexRoute
  '/admin/hajj/': typeof AdminHajjIndexRoute
  '/admin/packages/': typeof AdminPackagesIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/trips/': typeof AdminTripsIndexRoute
  '/admin/umrah/': typeof AdminUmrahIndexRoute
  '/admin/visas/': typeof AdminVisasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dubai': typeof DubaiRoute
  '/egypt': typeof EgyptRoute
  '/gallery': typeof GalleryRoute
  '/hajj': typeof HajjRoute
  '/qatar': typeof QatarRoute
  '/saudi': typeof SaudiRoute
  '/schengen': typeof SchengenRoute
  '/services': typeof ServicesRoute
  '/syria': typeof SyriaRoute
  '/turkey-trip': typeof TurkeyTripRoute
  '/uae': typeof UaeRoute
  '/uk': typeof UkRoute
  '/usa': typeof UsaRoute
  '/visa': typeof VisaRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/packages/$slug': typeof PackagesSlugRoute
  '/trips/$id': typeof TripsIdRoute
  '/umrah/$id': typeof UmrahIdRoute
  '/visa/$slug': typeof VisaSlugRoute
  '/admin': typeof AdminIndexRoute
  '/umrah': typeof UmrahIndexRoute
  '/admin/packages/$slug': typeof AdminPackagesSlugRoute
  '/admin/dubai': typeof AdminDubaiIndexRoute
  '/admin/egypt': typeof AdminEgyptIndexRoute
  '/admin/gallery': typeof AdminGalleryIndexRoute
  '/admin/hajj': typeof AdminHajjIndexRoute
  '/admin/packages': typeof AdminPackagesIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/admin/trips': typeof AdminTripsIndexRoute
  '/admin/umrah': typeof AdminUmrahIndexRoute
  '/admin/visas': typeof AdminVisasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dubai': typeof DubaiRoute
  '/egypt': typeof EgyptRoute
  '/gallery': typeof GalleryRoute
  '/hajj': typeof HajjRoute
  '/qatar': typeof QatarRoute
  '/saudi': typeof SaudiRoute
  '/schengen': typeof SchengenRoute
  '/services': typeof ServicesRoute
  '/syria': typeof SyriaRoute
  '/turkey-trip': typeof TurkeyTripRoute
  '/uae': typeof UaeRoute
  '/uk': typeof UkRoute
  '/umrah': typeof UmrahRouteWithChildren
  '/usa': typeof UsaRoute
  '/visa': typeof VisaRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/packages/$slug': typeof PackagesSlugRoute
  '/trips/$id': typeof TripsIdRoute
  '/umrah/$id': typeof UmrahIdRoute
  '/visa/$slug': typeof VisaSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/umrah/': typeof UmrahIndexRoute
  '/admin/packages/$slug': typeof AdminPackagesSlugRoute
  '/admin/dubai/': typeof AdminDubaiIndexRoute
  '/admin/egypt/': typeof AdminEgyptIndexRoute
  '/admin/gallery/': typeof AdminGalleryIndexRoute
  '/admin/hajj/': typeof AdminHajjIndexRoute
  '/admin/packages/': typeof AdminPackagesIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/trips/': typeof AdminTripsIndexRoute
  '/admin/umrah/': typeof AdminUmrahIndexRoute
  '/admin/visas/': typeof AdminVisasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dubai'
    | '/egypt'
    | '/gallery'
    | '/hajj'
    | '/qatar'
    | '/saudi'
    | '/schengen'
    | '/services'
    | '/syria'
    | '/turkey-trip'
    | '/uae'
    | '/uk'
    | '/umrah'
    | '/usa'
    | '/visa'
    | '/admin/login'
    | '/packages/$slug'
    | '/trips/$id'
    | '/umrah/$id'
    | '/visa/$slug'
    | '/admin/'
    | '/umrah/'
    | '/admin/packages/$slug'
    | '/admin/dubai/'
    | '/admin/egypt/'
    | '/admin/gallery/'
    | '/admin/hajj/'
    | '/admin/packages/'
    | '/admin/settings/'
    | '/admin/trips/'
    | '/admin/umrah/'
    | '/admin/visas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dubai'
    | '/egypt'
    | '/gallery'
    | '/hajj'
    | '/qatar'
    | '/saudi'
    | '/schengen'
    | '/services'
    | '/syria'
    | '/turkey-trip'
    | '/uae'
    | '/uk'
    | '/usa'
    | '/visa'
    | '/admin/login'
    | '/packages/$slug'
    | '/trips/$id'
    | '/umrah/$id'
    | '/visa/$slug'
    | '/admin'
    | '/umrah'
    | '/admin/packages/$slug'
    | '/admin/dubai'
    | '/admin/egypt'
    | '/admin/gallery'
    | '/admin/hajj'
    | '/admin/packages'
    | '/admin/settings'
    | '/admin/trips'
    | '/admin/umrah'
    | '/admin/visas'
  id:
    | '__root__'
    | '/'
    | '/dubai'
    | '/egypt'
    | '/gallery'
    | '/hajj'
    | '/qatar'
    | '/saudi'
    | '/schengen'
    | '/services'
    | '/syria'
    | '/turkey-trip'
    | '/uae'
    | '/uk'
    | '/umrah'
    | '/usa'
    | '/visa'
    | '/admin/login'
    | '/packages/$slug'
    | '/trips/$id'
    | '/umrah/$id'
    | '/visa/$slug'
    | '/admin/'
    | '/umrah/'
    | '/admin/packages/$slug'
    | '/admin/dubai/'
    | '/admin/egypt/'
    | '/admin/gallery/'
    | '/admin/hajj/'
    | '/admin/packages/'
    | '/admin/settings/'
    | '/admin/trips/'
    | '/admin/umrah/'
    | '/admin/visas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DubaiRoute: typeof DubaiRoute
  EgyptRoute: typeof EgyptRoute
  GalleryRoute: typeof GalleryRoute
  HajjRoute: typeof HajjRoute
  QatarRoute: typeof QatarRoute
  SaudiRoute: typeof SaudiRoute
  SchengenRoute: typeof SchengenRoute
  ServicesRoute: typeof ServicesRoute
  SyriaRoute: typeof SyriaRoute
  TurkeyTripRoute: typeof TurkeyTripRoute
  UaeRoute: typeof UaeRoute
  UkRoute: typeof UkRoute
  UmrahRoute: typeof UmrahRouteWithChildren
  UsaRoute: typeof UsaRoute
  VisaRoute: typeof VisaRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  PackagesSlugRoute: typeof PackagesSlugRoute
  TripsIdRoute: typeof TripsIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminPackagesSlugRoute: typeof AdminPackagesSlugRoute
  AdminDubaiIndexRoute: typeof AdminDubaiIndexRoute
  AdminEgyptIndexRoute: typeof AdminEgyptIndexRoute
  AdminGalleryIndexRoute: typeof AdminGalleryIndexRoute
  AdminHajjIndexRoute: typeof AdminHajjIndexRoute
  AdminPackagesIndexRoute: typeof AdminPackagesIndexRoute
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
  AdminTripsIndexRoute: typeof AdminTripsIndexRoute
  AdminUmrahIndexRoute: typeof AdminUmrahIndexRoute
  AdminVisasIndexRoute: typeof AdminVisasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visa': {
      id: '/visa'
      path: '/visa'
      fullPath: '/visa'
      preLoaderRoute: typeof VisaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usa': {
      id: '/usa'
      path: '/usa'
      fullPath: '/usa'
      preLoaderRoute: typeof UsaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/umrah': {
      id: '/umrah'
      path: '/umrah'
      fullPath: '/umrah'
      preLoaderRoute: typeof UmrahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uk': {
      id: '/uk'
      path: '/uk'
      fullPath: '/uk'
      preLoaderRoute: typeof UkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uae': {
      id: '/uae'
      path: '/uae'
      fullPath: '/uae'
      preLoaderRoute: typeof UaeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/turkey-trip': {
      id: '/turkey-trip'
      path: '/turkey-trip'
      fullPath: '/turkey-trip'
      preLoaderRoute: typeof TurkeyTripRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/syria': {
      id: '/syria'
      path: '/syria'
      fullPath: '/syria'
      preLoaderRoute: typeof SyriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schengen': {
      id: '/schengen'
      path: '/schengen'
      fullPath: '/schengen'
      preLoaderRoute: typeof SchengenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saudi': {
      id: '/saudi'
      path: '/saudi'
      fullPath: '/saudi'
      preLoaderRoute: typeof SaudiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qatar': {
      id: '/qatar'
      path: '/qatar'
      fullPath: '/qatar'
      preLoaderRoute: typeof QatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hajj': {
      id: '/hajj'
      path: '/hajj'
      fullPath: '/hajj'
      preLoaderRoute: typeof HajjRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/egypt': {
      id: '/egypt'
      path: '/egypt'
      fullPath: '/egypt'
      preLoaderRoute: typeof EgyptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dubai': {
      id: '/dubai'
      path: '/dubai'
      fullPath: '/dubai'
      preLoaderRoute: typeof DubaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/umrah/': {
      id: '/umrah/'
      path: '/'
      fullPath: '/umrah/'
      preLoaderRoute: typeof UmrahIndexRouteImport
      parentRoute: typeof UmrahRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visa/$slug': {
      id: '/visa/$slug'
      path: '/$slug'
      fullPath: '/visa/$slug'
      preLoaderRoute: typeof VisaSlugRouteImport
      parentRoute: typeof VisaRoute
    }
    '/umrah/$id': {
      id: '/umrah/$id'
      path: '/$id'
      fullPath: '/umrah/$id'
      preLoaderRoute: typeof UmrahIdRouteImport
      parentRoute: typeof UmrahRoute
    }
    '/trips/$id': {
      id: '/trips/$id'
      path: '/trips/$id'
      fullPath: '/trips/$id'
      preLoaderRoute: typeof TripsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/$slug': {
      id: '/packages/$slug'
      path: '/packages/$slug'
      fullPath: '/packages/$slug'
      preLoaderRoute: typeof PackagesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/visas/': {
      id: '/admin/visas/'
      path: '/admin/visas'
      fullPath: '/admin/visas/'
      preLoaderRoute: typeof AdminVisasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/umrah/': {
      id: '/admin/umrah/'
      path: '/admin/umrah'
      fullPath: '/admin/umrah/'
      preLoaderRoute: typeof AdminUmrahIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/trips/': {
      id: '/admin/trips/'
      path: '/admin/trips'
      fullPath: '/admin/trips/'
      preLoaderRoute: typeof AdminTripsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings/': {
      id: '/admin/settings/'
      path: '/admin/settings'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AdminSettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/packages/': {
      id: '/admin/packages/'
      path: '/admin/packages'
      fullPath: '/admin/packages/'
      preLoaderRoute: typeof AdminPackagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/hajj/': {
      id: '/admin/hajj/'
      path: '/admin/hajj'
      fullPath: '/admin/hajj/'
      preLoaderRoute: typeof AdminHajjIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/gallery/': {
      id: '/admin/gallery/'
      path: '/admin/gallery'
      fullPath: '/admin/gallery/'
      preLoaderRoute: typeof AdminGalleryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/egypt/': {
      id: '/admin/egypt/'
      path: '/admin/egypt'
      fullPath: '/admin/egypt/'
      preLoaderRoute: typeof AdminEgyptIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dubai/': {
      id: '/admin/dubai/'
      path: '/admin/dubai'
      fullPath: '/admin/dubai/'
      preLoaderRoute: typeof AdminDubaiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/packages/$slug': {
      id: '/admin/packages/$slug'
      path: '/admin/packages/$slug'
      fullPath: '/admin/packages/$slug'
      preLoaderRoute: typeof AdminPackagesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface UmrahRouteChildren {
  UmrahIdRoute: typeof UmrahIdRoute
  UmrahIndexRoute: typeof UmrahIndexRoute
}

const UmrahRouteChildren: UmrahRouteChildren = {
  UmrahIdRoute: UmrahIdRoute,
  UmrahIndexRoute: UmrahIndexRoute,
}

const UmrahRouteWithChildren = UmrahRoute._addFileChildren(UmrahRouteChildren)

interface VisaRouteChildren {
  VisaSlugRoute: typeof VisaSlugRoute
}

const VisaRouteChildren: VisaRouteChildren = {
  VisaSlugRoute: VisaSlugRoute,
}

const VisaRouteWithChildren = VisaRoute._addFileChildren(VisaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DubaiRoute: DubaiRoute,
  EgyptRoute: EgyptRoute,
  GalleryRoute: GalleryRoute,
  HajjRoute: HajjRoute,
  QatarRoute: QatarRoute,
  SaudiRoute: SaudiRoute,
  SchengenRoute: SchengenRoute,
  ServicesRoute: ServicesRoute,
  SyriaRoute: SyriaRoute,
  TurkeyTripRoute: TurkeyTripRoute,
  UaeRoute: UaeRoute,
  UkRoute: UkRoute,
  UmrahRoute: UmrahRouteWithChildren,
  UsaRoute: UsaRoute,
  VisaRoute: VisaRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  PackagesSlugRoute: PackagesSlugRoute,
  TripsIdRoute: TripsIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminPackagesSlugRoute: AdminPackagesSlugRoute,
  AdminDubaiIndexRoute: AdminDubaiIndexRoute,
  AdminEgyptIndexRoute: AdminEgyptIndexRoute,
  AdminGalleryIndexRoute: AdminGalleryIndexRoute,
  AdminHajjIndexRoute: AdminHajjIndexRoute,
  AdminPackagesIndexRoute: AdminPackagesIndexRoute,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
  AdminTripsIndexRoute: AdminTripsIndexRoute,
  AdminUmrahIndexRoute: AdminUmrahIndexRoute,
  AdminVisasIndexRoute: AdminVisasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
