/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisaRouteImport } from './routes/visa'
import { Route as UsaRouteImport } from './routes/usa'
import { Route as UmrahRouteImport } from './routes/umrah'
import { Route as UkRouteImport } from './routes/uk'
import { Route as UaeRouteImport } from './routes/uae'
import { Route as SyriaRouteImport } from './routes/syria'
import { Route as SchengenRouteImport } from './routes/schengen'
import { Route as SaudiRouteImport } from './routes/saudi'
import { Route as QatarRouteImport } from './routes/qatar'
import { Route as HajjRouteImport } from './routes/hajj'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UmrahIndexRouteImport } from './routes/umrah.index'
import { Route as UmrahIdRouteImport } from './routes/umrah.$id'

const VisaRoute = VisaRouteImport.update({
  id: '/visa',
  path: '/visa',
  getParentRoute: () => rootRouteImport,
} as any)
const UsaRoute = UsaRouteImport.update({
  id: '/usa',
  path: '/usa',
  getParentRoute: () => rootRouteImport,
} as any)
const UmrahRoute = UmrahRouteImport.update({
  id: '/umrah',
  path: '/umrah',
  getParentRoute: () => rootRouteImport,
} as any)
const UkRoute = UkRouteImport.update({
  id: '/uk',
  path: '/uk',
  getParentRoute: () => rootRouteImport,
} as any)
const UaeRoute = UaeRouteImport.update({
  id: '/uae',
  path: '/uae',
  getParentRoute: () => rootRouteImport,
} as any)
const SyriaRoute = SyriaRouteImport.update({
  id: '/syria',
  path: '/syria',
  getParentRoute: () => rootRouteImport,
} as any)
const SchengenRoute = SchengenRouteImport.update({
  id: '/schengen',
  path: '/schengen',
  getParentRoute: () => rootRouteImport,
} as any)
const SaudiRoute = SaudiRouteImport.update({
  id: '/saudi',
  path: '/saudi',
  getParentRoute: () => rootRouteImport,
} as any)
const QatarRoute = QatarRouteImport.update({
  id: '/qatar',
  path: '/qatar',
  getParentRoute: () => rootRouteImport,
} as any)
const HajjRoute = HajjRouteImport.update({
  id: '/hajj',
  path: '/hajj',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UmrahIndexRoute = UmrahIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UmrahRoute,
} as any)
const UmrahIdRoute = UmrahIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => UmrahRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hajj': typeof HajjRoute
  '/qatar': typeof QatarRoute
  '/saudi': typeof SaudiRoute
  '/schengen': typeof SchengenRoute
  '/syria': typeof SyriaRoute
  '/uae': typeof UaeRoute
  '/uk': typeof UkRoute
  '/umrah': typeof UmrahRouteWithChildren
  '/usa': typeof UsaRoute
  '/visa': typeof VisaRoute
  '/umrah/$id': typeof UmrahIdRoute
  '/umrah/': typeof UmrahIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hajj': typeof HajjRoute
  '/qatar': typeof QatarRoute
  '/saudi': typeof SaudiRoute
  '/schengen': typeof SchengenRoute
  '/syria': typeof SyriaRoute
  '/uae': typeof UaeRoute
  '/uk': typeof UkRoute
  '/usa': typeof UsaRoute
  '/visa': typeof VisaRoute
  '/umrah/$id': typeof UmrahIdRoute
  '/umrah': typeof UmrahIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hajj': typeof HajjRoute
  '/qatar': typeof QatarRoute
  '/saudi': typeof SaudiRoute
  '/schengen': typeof SchengenRoute
  '/syria': typeof SyriaRoute
  '/uae': typeof UaeRoute
  '/uk': typeof UkRoute
  '/umrah': typeof UmrahRouteWithChildren
  '/usa': typeof UsaRoute
  '/visa': typeof VisaRoute
  '/umrah/$id': typeof UmrahIdRoute
  '/umrah/': typeof UmrahIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/hajj'
    | '/qatar'
    | '/saudi'
    | '/schengen'
    | '/syria'
    | '/uae'
    | '/uk'
    | '/umrah'
    | '/usa'
    | '/visa'
    | '/umrah/$id'
    | '/umrah/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/hajj'
    | '/qatar'
    | '/saudi'
    | '/schengen'
    | '/syria'
    | '/uae'
    | '/uk'
    | '/usa'
    | '/visa'
    | '/umrah/$id'
    | '/umrah'
  id:
    | '__root__'
    | '/'
    | '/hajj'
    | '/qatar'
    | '/saudi'
    | '/schengen'
    | '/syria'
    | '/uae'
    | '/uk'
    | '/umrah'
    | '/usa'
    | '/visa'
    | '/umrah/$id'
    | '/umrah/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HajjRoute: typeof HajjRoute
  QatarRoute: typeof QatarRoute
  SaudiRoute: typeof SaudiRoute
  SchengenRoute: typeof SchengenRoute
  SyriaRoute: typeof SyriaRoute
  UaeRoute: typeof UaeRoute
  UkRoute: typeof UkRoute
  UmrahRoute: typeof UmrahRouteWithChildren
  UsaRoute: typeof UsaRoute
  VisaRoute: typeof VisaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visa': {
      id: '/visa'
      path: '/visa'
      fullPath: '/visa'
      preLoaderRoute: typeof VisaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usa': {
      id: '/usa'
      path: '/usa'
      fullPath: '/usa'
      preLoaderRoute: typeof UsaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/umrah': {
      id: '/umrah'
      path: '/umrah'
      fullPath: '/umrah'
      preLoaderRoute: typeof UmrahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uk': {
      id: '/uk'
      path: '/uk'
      fullPath: '/uk'
      preLoaderRoute: typeof UkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uae': {
      id: '/uae'
      path: '/uae'
      fullPath: '/uae'
      preLoaderRoute: typeof UaeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/syria': {
      id: '/syria'
      path: '/syria'
      fullPath: '/syria'
      preLoaderRoute: typeof SyriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schengen': {
      id: '/schengen'
      path: '/schengen'
      fullPath: '/schengen'
      preLoaderRoute: typeof SchengenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saudi': {
      id: '/saudi'
      path: '/saudi'
      fullPath: '/saudi'
      preLoaderRoute: typeof SaudiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qatar': {
      id: '/qatar'
      path: '/qatar'
      fullPath: '/qatar'
      preLoaderRoute: typeof QatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hajj': {
      id: '/hajj'
      path: '/hajj'
      fullPath: '/hajj'
      preLoaderRoute: typeof HajjRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/umrah/': {
      id: '/umrah/'
      path: '/'
      fullPath: '/umrah/'
      preLoaderRoute: typeof UmrahIndexRouteImport
      parentRoute: typeof UmrahRoute
    }
    '/umrah/$id': {
      id: '/umrah/$id'
      path: '/$id'
      fullPath: '/umrah/$id'
      preLoaderRoute: typeof UmrahIdRouteImport
      parentRoute: typeof UmrahRoute
    }
  }
}

interface UmrahRouteChildren {
  UmrahIdRoute: typeof UmrahIdRoute
  UmrahIndexRoute: typeof UmrahIndexRoute
}

const UmrahRouteChildren: UmrahRouteChildren = {
  UmrahIdRoute: UmrahIdRoute,
  UmrahIndexRoute: UmrahIndexRoute,
}

const UmrahRouteWithChildren = UmrahRoute._addFileChildren(UmrahRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HajjRoute: HajjRoute,
  QatarRoute: QatarRoute,
  SaudiRoute: SaudiRoute,
  SchengenRoute: SchengenRoute,
  SyriaRoute: SyriaRoute,
  UaeRoute: UaeRoute,
  UkRoute: UkRoute,
  UmrahRoute: UmrahRouteWithChildren,
  UsaRoute: UsaRoute,
  VisaRoute: VisaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
