-- Connect the existing public trip pages to the simplified trips CMS.
-- This keeps the four-table CMS and only adds page/detail fields to public.trips.

ALTER TABLE public.trips
  ADD COLUMN IF NOT EXISTS page_key TEXT,
  ADD COLUMN IF NOT EXISTS room_type TEXT,
  ADD COLUMN IF NOT EXISTS double_price NUMERIC(12, 2)
    CHECK (double_price IS NULL OR double_price >= 0),
  ADD COLUMN IF NOT EXISTS triple_price NUMERIC(12, 2)
    CHECK (triple_price IS NULL OR triple_price >= 0),
  ADD COLUMN IF NOT EXISTS quad_price NUMERIC(12, 2)
    CHECK (quad_price IS NULL OR quad_price >= 0),
  ADD COLUMN IF NOT EXISTS additional_image_urls TEXT[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS madinah_image_url TEXT;

-- Existing records created by the current admin are assigned to their public page.
UPDATE public.trips
SET page_key = CASE
  WHEN category = 'umrah' THEN 'umrah'
  ELSE 'general'
END
WHERE page_key IS NULL;

ALTER TABLE public.trips
  ALTER COLUMN page_key SET DEFAULT 'general',
  ALTER COLUMN page_key SET NOT NULL;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'trips_page_key_check'
      AND conrelid = 'public.trips'::regclass
  ) THEN
    ALTER TABLE public.trips
      ADD CONSTRAINT trips_page_key_check
      CHECK (page_key IN ('general', 'umrah', 'hajj', 'egypt', 'dubai'));
  END IF;
END
$$;

CREATE INDEX IF NOT EXISTS trips_page_key_idx ON public.trips (page_key);

-- Seed the packages that were previously hard-coded in the public pages.
-- ON CONFLICT DO NOTHING ensures later CMS edits are never overwritten.
INSERT INTO public.trips (
  id,
  title,
  category,
  page_key,
  description,
  start_date,
  end_date,
  price,
  currency,
  makkah_hotel,
  madinah_hotel,
  meals,
  nights,
  status,
  main_image_url,
  room_type,
  double_price,
  triple_price,
  quad_price,
  additional_image_urls,
  madinah_image_url
)
VALUES
  (
    'c0e50000-0000-4000-8000-000000000001',
    'فجر البديع 6',
    'umrah',
    'umrah',
    '6 ليالي مكة - ليلتين المدينة',
    '2026-07-01',
    NULL,
    NULL,
    'JOD',
    'فجر البديع 6',
    'المركزية',
    'بدون وجبات',
    8,
    'available',
    '/images/hotels/fajr/main.png',
    'رباعي',
    235,
    215,
    190,
    ARRAY['/images/hotels/fajr/1.jpg', '/images/hotels/fajr/2.jpg', '/images/hotels/fajr/3.jpg'],
    '/images/madinah.jpg/madinah.jpg'
  ),
  (
    'c0e50000-0000-4000-8000-000000000002',
    'فيوليت 2',
    'umrah',
    'umrah',
    '6 ليالي مكة - ليلتين المدينة',
    '2026-07-08',
    NULL,
    NULL,
    'JOD',
    'فيوليت 2',
    'المركزية',
    'بدون وجبات',
    8,
    'available',
    '/images/hotels/violet/main.png',
    'ثلاثي',
    250,
    220,
    210,
    ARRAY['/images/hotels/violet/1.jpg', '/images/hotels/violet/2.jpg', '/images/hotels/violet/3.jpg'],
    '/images/madinah.jpg/madinah.jpg'
  ),
  (
    'c0e50000-0000-4000-8000-000000000003',
    'رمادا التيسير',
    'umrah',
    'umrah',
    '6 ليالي مكة - ليلتين المدينة',
    '2026-07-15',
    NULL,
    NULL,
    'JOD',
    'رمادا التيسير',
    'المركزية',
    'بدون وجبات',
    8,
    'available',
    '/images/hotels/ramada/main.png',
    'ثنائي',
    255,
    230,
    215,
    ARRAY['/images/hotels/ramada/1.jpg', '/images/hotels/ramada/2.jpg', '/images/hotels/ramada/3.jpg'],
    '/images/madinah.jpg/madinah.jpg'
  ),
  (
    'c0e50000-0000-4000-8000-000000000004',
    'تاج بارك',
    'umrah',
    'umrah',
    '6 ليالي مكة - ليلتين المدينة',
    '2026-07-22',
    NULL,
    NULL,
    'JOD',
    'تاج بارك',
    'المركزية',
    'إفطار مكة فقط',
    8,
    'available',
    '/images/hotels/tajpark/main.png',
    'رباعي',
    280,
    240,
    220,
    ARRAY['/images/hotels/tajpark/1.jpg', '/images/hotels/tajpark/2.jpg', '/images/hotels/tajpark/3.jpg', '/images/hotels/tajpark/4.jpg'],
    '/images/madinah.jpg/madinah.jpg'
  ),
  (
    'c0e50000-0000-4000-8000-000000000005',
    'الأيباء',
    'umrah',
    'umrah',
    '6 ليالي مكة - ليلتين المدينة',
    '2026-07-22',
    NULL,
    NULL,
    'JOD',
    'الأيباء',
    'المركزية',
    'بدون وجبات',
    8,
    'available',
    '/images/hotels/alebaa/main.png',
    'رباعي',
    375,
    315,
    285,
    ARRAY['/images/hotels/alebaa/1.jpg', '/images/hotels/alebaa/2.jpg', '/images/hotels/alebaa/3.jpg'],
    '/images/madinah.jpg/madinah.jpg'
  ),
  (
    'c0e50000-0000-4000-8000-000000000006',
    'أنجم',
    'umrah',
    'umrah',
    '6 ليالي مكة - ليلتين المدينة',
    '2026-07-22',
    NULL,
    NULL,
    'JOD',
    'أنجم',
    'المركزية',
    'إفطار مكة فقط',
    8,
    'available',
    '/images/hotels/anjum/main.png',
    'ثنائي',
    470,
    400,
    380,
    ARRAY['/images/hotels/anjum/1.jpg', '/images/hotels/anjum/2.jpg', '/images/hotels/anjum/3.jpg'],
    '/images/madinah.jpg/madinah.jpg'
  ),
  (
    'c0e50000-0000-4000-8000-000000000101',
    'الحج 1448 هـ / 2027 م',
    'tourism',
    'hajj',
    'يسر شركة قيصر للسياحة والسفر الإعلان عن فتح باب التسجيل لموسم الحج لعام 1448 هـ / 2027 م.',
    '2027-05-14',
    '2027-05-19',
    NULL,
    'JOD',
    NULL,
    NULL,
    NULL,
    6,
    'available',
    '/images/hajj-banner.jpg',
    NULL,
    NULL,
    NULL,
    NULL,
    '{}',
    NULL
  ),
  (
    'c0e50000-0000-4000-8000-000000000201',
    'Atlantis The Palm',
    'tourism',
    'egypt',
    NULL,
    NULL,
    NULL,
    1650,
    'AED',
    NULL,
    NULL,
    NULL,
    0,
    'available',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '{}',
    NULL
  ),
  (
    'c0e50000-0000-4000-8000-000000000202',
    'Address Sky View',
    'tourism',
    'egypt',
    NULL,
    NULL,
    NULL,
    1250,
    'AED',
    NULL,
    NULL,
    NULL,
    0,
    'available',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '{}',
    NULL
  ),
  (
    'c0e50000-0000-4000-8000-000000000203',
    'Armani Hotel',
    'tourism',
    'egypt',
    NULL,
    NULL,
    NULL,
    1950,
    'AED',
    NULL,
    NULL,
    NULL,
    0,
    'available',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '{}',
    NULL
  ),
  (
    'c0e50000-0000-4000-8000-000000000204',
    'JW Marriott Marquis',
    'tourism',
    'egypt',
    NULL,
    NULL,
    NULL,
    1100,
    'AED',
    NULL,
    NULL,
    NULL,
    0,
    'available',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '{}',
    NULL
  ),
  (
    'c0e50000-0000-4000-8000-000000000301',
    'Atlantis The Palm',
    'tourism',
    'dubai',
    NULL,
    NULL,
    NULL,
    1650,
    'AED',
    NULL,
    NULL,
    NULL,
    0,
    'available',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '{}',
    NULL
  ),
  (
    'c0e50000-0000-4000-8000-000000000302',
    'Address Sky View',
    'tourism',
    'dubai',
    NULL,
    NULL,
    NULL,
    1250,
    'AED',
    NULL,
    NULL,
    NULL,
    0,
    'available',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '{}',
    NULL
  ),
  (
    'c0e50000-0000-4000-8000-000000000303',
    'Armani Hotel',
    'tourism',
    'dubai',
    NULL,
    NULL,
    NULL,
    1950,
    'AED',
    NULL,
    NULL,
    NULL,
    0,
    'available',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '{}',
    NULL
  ),
  (
    'c0e50000-0000-4000-8000-000000000304',
    'JW Marriott Marquis',
    'tourism',
    'dubai',
    NULL,
    NULL,
    NULL,
    1100,
    'AED',
    NULL,
    NULL,
    NULL,
    0,
    'available',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '{}',
    NULL
  )
ON CONFLICT (id) DO NOTHING;
